### ISSUE TITLE
 I have problem

### ISSUE THREAD

**Issue by JavadKohsari** [mkheirkhah/mptcp#10]
I want configure "nanonetworks module" on ns3 ver3.32 but I have this error

![Screenshot (17)](https://user-images.githubusercontent.com/76438468/102784955-6143b900-43b2-11eb-9b51-ae770720239b.png)
![Screenshot (18)](https://user-images.githubusercontent.com/76438468/102784996-73bdf280-43b2-11eb-9edf-7386d6d95ebb.png)

//////////
[1911/2955] Compiling src/nanonetworks/model/nanonode-nano-device.cc
In file included from ../src/nanonetworks/model/nano-mac-entity.cc:27:0:
../src/nanonetworks/model/nano-spectrum-channel.h:54:20: error: conflicting return type specified for ‘virtual uint32_t ns3::NanoSpectrumChannel::GetNDevices() const’
   virtual uint32_t GetNDevices (void) const;
                    ^~~~~~~~~~~
In file included from ./ns3/spectrum-channel.h:27:0,
                 from ../src/nanonetworks/model/nano-spectrum-channel.h:25,
                 from ../src/nanonetworks/model/nano-mac-entity.cc:27:
./ns3/channel.h:68:23: error:   overriding ‘virtual std::size_t ns3::Channel::GetNDevices() const’
   virtual std::size_t GetNDevices (void) const = 0;
                       ^~~~~~~~~~~

Waf: Leaving directory `/home/jk/ns-allinone-3.32/ns-3.32/build'
Build failed
 -> task in 'ns3-nanonetworks' failed with exit status 1 (run with -v to display more information)
//////please help me
how can I solve it?

**Comment by skozy** [comment]
Hello im having same issue. Any solution yet

**Comment by mkheirkhah** [comment]
This code has been developed and tested on NS-3.19.
