### ISSUE TITLE
MPTCP Demo

### ISSUE THREAD

**Issue by liuhailove** [mkheirkhah/mptcp#3]
Through you have release your MPTCP's code,but it seems have enough demos.Your mptcp.cc just have one path,how can i have two subflow path?

**Comment by liuhailove** [comment]
I have write a demo have tow Path,but it seems run incorrect.Can you tell me how to correct it? Thank you very much.
int
main(int argc, char *argv[])
{
  LogComponentEnable("MpTcpSocketBase", LOG_INFO);

  Config::SetDefault("ns3::Ipv4GlobalRouting::FlowEcmpRouting", BooleanValue(true));
  Config::SetDefault("ns3::TcpSocket::SegmentSize", UintegerValue(1400));
  Config::SetDefault("ns3::TcpSocket::DelAckCount", UintegerValue(0));
  Config::SetDefault("ns3::DropTailQueue::Mode", StringValue("QUEUE_MODE_PACKETS"));
  Config::SetDefault("ns3::DropTailQueue::MaxPackets", UintegerValue(100));
  Config::SetDefault("ns3::TcpL4Protocol::SocketType", TypeIdValue(MpTcpSocketBase::GetTypeId()));
  Config::SetDefault("ns3::MpTcpSocketBase::MaxSubflows", UintegerValue(8)); // Sink
  //Config::SetDefault("ns3::MpTcpSocketBase::CongestionControl", StringValue("RTT_Compensator"));
  //Config::SetDefault("ns3::MpTcpSocketBase::PathManagement", StringValue("NdiffPorts"));

 // NodeContainer nodes;
 // nodes.Create(2);
   /\* Build nodes. */
  NodeContainer term_0;
  term_0.Create(1);
  NodeContainer term_1;
  term_1.Create(1);

 // PointToPointHelper pointToPoint;
 // pointToPoint.SetDeviceAttribute("DataRate", StringValue("100Mbps"));
//  pointToPoint.SetChannelAttribute("Delay", StringValue("1ms"));
 /\* Build link. */
  PointToPointHelper p2p_p2p_0;
  p2p_p2p_0.SetDeviceAttribute("DataRate", DataRateValue(100000000));
  p2p_p2p_0.SetChannelAttribute("Delay", TimeValue(MilliSeconds(1)));
  PointToPointHelper p2p_p2p_1;
  p2p_p2p_1.SetDeviceAttribute("DataRate", DataRateValue(100000000));
  p2p_p2p_1.SetChannelAttribute("Delay", TimeValue(MilliSeconds(1)));

  //NetDeviceContainer devices;
  //devices = pointToPoint.Install(nodes);

   /\* Build link net device container. _/
  NodeContainer all_p2p_0;
  all_p2p_0.Add(term_0);
  all_p2p_0.Add(term_1);
  NetDeviceContainer ndc_p2p_0 = p2p_p2p_0.Install(all_p2p_0);
  NodeContainer all_p2p_1;
  all_p2p_1.Add(term_0);
  all_p2p_1.Add(term_1);
  NetDeviceContainer ndc_p2p_1 = p2p_p2p_1.Install(all_p2p_1);
 // InternetStackHelper internet;
 // internet.Install(nodes);
 /_ Install the IP stack. */
  InternetStackHelper internetStackH;
  internetStackH.Install(term_0);
  internetStackH.Install(term_1);

  //Ipv4AddressHelper ipv4;
  //ipv4.SetBase("10.1.1.0", "255.255.255.0");
  //Ipv4InterfaceContainer i = ipv4.Assign(devices);
    /\* IP assign. */
  Ipv4AddressHelper ipv4;
  ipv4.SetBase("10.0.0.0", "255.255.255.0");
  Ipv4InterfaceContainer iface_ndc_p2p_0 = ipv4.Assign(ndc_p2p_0);
  ipv4.SetBase("10.0.1.0", "255.255.255.0");
  Ipv4InterfaceContainer iface_ndc_p2p_1 = ipv4.Assign(ndc_p2p_1);

  uint16_t port = 9;
  MpTcpPacketSinkHelper sink("ns3::TcpSocketFactory", InetSocketAddress(Ipv4Address::GetAny(), port));
  ApplicationContainer sinkApps = sink.Install(term_1.Get(0));
  sinkApps.Start(Seconds(0.0));
  sinkApps.Stop(Seconds(10.0));

  MpTcpBulkSendHelper source("ns3::TcpSocketFactory", InetSocketAddress(Ipv4Address(iface_ndc_p2p_0.GetAddress(0)), port));
  source.SetAttribute("MaxBytes", UintegerValue(0));
  ApplicationContainer sourceApps = source.Install(term_0.Get(0));
  sourceApps.Start(Seconds(0.0));
  sourceApps.Stop(Seconds(100.0));

  NS_LOG_INFO ("Run Simulation.");
  Simulator::Stop(Seconds(200.0));
  Simulator::Run();
  Simulator::Destroy();
  NS_LOG_INFO ("Done.");

}

**Comment by mkheirkhah** [comment]
Hi, I have already sent an email to you for this.

**Comment by blackthunder0812** [comment]
Send me one, please!
My mailbox: bachngocson0812@gmail.com
Thanks!

**Comment by nguyentdkhoa** [comment]
Hi, could you please send me one?
Thank you! 
Email: khoantd2010@gmail.com

**Comment by blackthunder0812** [comment]
Sorry, I didn't receive a reply from him, neither. But that code worked,
maybe he fixed it.

---

Bạch Ngọc Sơn@sonbn.cf
CTES - SoICT - HUST
(+84) 165 345 8875
School of Information and Communication Technology http://soict.hust.vn/
Center for Training of Excellent Students http://ctes.hust.edu.vn/
Hanoi University of Science and Technology http://www.hust.edu.vn/
http://www.facebook.com/CtrlG
http://profiles.google.com/112138539664656477287
http://pulse.yahoo.com/_XTJPSSVM5HSXS3HNBW2Q2PXFWY

## https://twitter.com/sonbn812

**Comment by nguyentdkhoa** [comment]
Thanks for letting me know. The codes worked fine, even while installation got minor errors but they don't affect much on its functions.

**Comment by lichengpeng** [comment]
Hi man! Could you please send me your MPTCP code? I'm learning this almost one month, but still cannot handle this...... My email: 840082851@qq.com

**Comment by tcptsai** [comment]
Hello! Could anyone send me the MPTCP code? I'm still in trouble about it... My email is ddmail2009@gmail.com   Thanks!

**Comment by rahulhada** [comment]
Please share the code for two flow demo for mptcp scenario.

**Comment by musobi** [comment]
anyone with idea on  how to create two subflows  one for LTE and the second is for Wi-Fi by using MPTCP by Morteza.  I can create subflows of the same interface only say LTE or Wi-Fi, Now i want to create two subflows of different interfaces i.e one for LTE and the other for Wi-Fi. Please help me my email is dntugwa@gmail.com

**Comment by ghf2016** [comment]
hi, can you send me your MPTCP code with tow subflows? I  just start learning MPTCP in ns3... Thank you so much,,    my email: ljc091111@163.com

**Comment by lihonglin2007** [comment]
Hello, cound anyone send me your MPTCP code with three subflows or two subflows? I just start learning MPTCP in ns3. Please help me. Thank you so much. My email: 1228044911@qq.com

**Comment by rahulhada** [comment]
What kind of scenario you are trying to simulate ?

With Best Regards,

Rahul

**Comment by lihonglin2007** [comment]
Thank you very much for your reply!

I consider a heterogeneous network consisting of 4G, 3G and WiFi which are generally equipped in a mobile device. The sender communicates with the receiver via three disjoint paths. Both the sender and the receiver support concurrent multipath transfer by implementing MPTCP. Each path is a subflow of
a MPTCP connection.

However I do not know how to simulate the scenario? If you have some advices or codes and don't mind, please help me? Thanks anyway!

With Best Regards,
Lee

**Comment by musobi** [comment]
Hello i can only simulate MPTCP with subflows of the same interface let say
LTE or Wi-Fi, i have not been able to simulate subflows from heterogeneous
network using Morteza Code base. Please we need a help from anybody who can
simulate in that scenario.

**Comment by ghost** [comment]
send me also this code file please:   jalpakumari143@gmail.com

**Comment by Justhiro55** [comment]
Please send me the demo code as well. 
JustHiro271@gmail.com

**Comment by GLtangzero** [comment]
Please send the demo code:
qlws116@gmail.com

**Comment by GLtangzero** [comment]
@liuhailove 
@mkheirkhah 
@blackthunder0812 
Hello could please share the document which could build several subflows?
Thanks
