### ISSUE TITLE
Can you givem some advice on a clean way to get the throughput of subflows during simulation time?

### ISSUE THREAD

**Issue by jianwel** [mkheirkhah/mptcp#5]
Hi Morteza,

  Thanks for sharing your code! I want to get the average throughput and RTT of each subflow (in say 5s) during simulation. Could you give some suggestions on how I can do that?
 Basically, I want to a struct for every subflow. The last two entries will be updated dynamically.
 `{ sourceAddr,
    sourcePort
   destAddr,
  destPort,
   lastMeasureThroughput,
 lastMeasureRTT
 }`
  For RTT, I saw there is `EstimateRtt` function and `lastMeasureRtt` variable. And, I saw  the first four entries are members of MpTcpSubFlow. So, the main question now is where in the code should I measure the `lastMeasureThroughput` for each subflow, and how can I measure that? There is a `uint64_t bandwidth;` in MpTcpSubFlow, but that's not from measurement, right?
 Can I use `uint32_t TxSeqNumber;       // Subflow's next expected sequence number to send
  uint32_t RxSeqNumber;       // Subflow's next expected sequence number to receive`. What will be the behavior of these seq numbers when one subflow breaks and comes back due to wireless connection link quality change during mobility. Will it be a new subflow?

Thanks,
Jayway

**Comment by mkheirkhah** [comment]
Hi Jayway,

You need to call a function called MpTcpSubFlow::StartTracing() within mp-tcp-socket-base.cc. This function automatically plots (at the end of your simulation) all you need on per subflow basis (RTT, CWND, SST, and etc.). 

At the moment this can be activated via ns3 attribute system (in your simulation configuration file) with two (boolean) parameters: LargePlotting and ShortPlotting. For example with the following syntax: Config::SetDefault("ns3::MpTcpSocketBase::LargePlotting", BooleanValue(true)). However,  this does not work if the flow type is not defined (e.g. whether it is large or short) when they are scheduled.

A quick fix for you to activate this function on every simulation is to remove the **if** condition in the line 555 of the mp-tcp-socket-base.cc class.

Please email me if you have any question.

Morteza

**Comment by jianwel** [comment]
Hi Morteza,

   I recently find out that your MPTCP code only work with global routing.
It always fail to connect when I test with a static routing set for either
wifi or LTE. I tested the same routing with non-mptcp TCP stack and
application, and they work pretty well. Attached is my code.
  Do you have any hints on what might causes this problem? I want to use
static routing, since LTE module in the NS3 does not support the global
routing. I need to figure this out ASAP. If you could give a brief reply,
it will be really helpful to me.

Thanks,
Jay

On Sun, Sep 18, 2016 at 8:07 AM, Morteza Kheirkhah <notifications@github.com

**Comment by trinhnguyenbao86** [comment]
Hi Morteza.
I tried to run the simulation and capture the following .pcap file.
I saw some weird things about TCP congestion window on each subflow as it does not change or vary according to traffic, it always keep as 65535.
COuld you please let me know if there is something in the code of mptcp that I should take into account ?

Thank you very much.

![wireshark_mptcp](https://user-images.githubusercontent.com/19197045/45976877-dee7b580-c03f-11e8-9241-cd9a39a719fd.png)
